version: '3'

networks:
  default:
    external: true
    name: ${NETWORK_NAME:-selenoid}

services:

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  
  selenoid:
    tty: true
    image: aerokube/selenoid:latest-release
    volumes:
      - "./config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "${NETWORK_NAME:-selenoid}" ]
    healthcheck:
      test: [ "CMD", "curl", "localhost:4444/ping" ]
    ports:
      - "4444:4444"
   
  
  tests:
    tty: true
    build: .
    image: tests_bankrot
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 30 && pytest tests/test_main_page.py -s -l -v --browser=chrome -n=1 --alluredir=allure-results --url=https://bankrot.fedresurs.ru/'
    depends_on:
      - selenoid
    volumes:
      - .:/workdir
